services:
    web-server:
      image: caddy:2.11.4-alpine
      container_name: web-server
      environment:
        - CADDY_HOST=${CADDY_HOST:-localhost}
      volumes:
        - ${PROJECT_ROOT}/web/Caddyfile:/etc/caddy/Caddyfile
        - ${PROJECT_ROOT}/web/public:/web/public
        - caddy_data:/data
      ports:
        - "80:80"
        - "443:443"
      restart: unless-stopped

    todoapp:
      build:
        context: ${PROJECT_ROOT}
        dockerfile: ${PROJECT_ROOT}/cmd/todoapp/Dockerfile
      container_name: todoapp
      environment:
        - HTTP_ADDR=:5050
        - HTTP_SHUTDOWN_TIMEOUT=${HTTP_SHUTDOWN_TIMEOUT}
        - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
        - POSTGRES_HOST=todoapp-postgres
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_TIMEOUT=${POSTGRES_TIMEOUT}
        - LOGGER_LEVEL=${LOGGER_LEVEL}
        - TIME_ZONE=${TIME_ZONE}
        - LOGGER_FOLDER=/app/out/logs
      volumes:
        - ${PROJECT_ROOT}/out/logs:/app/out/logs
      ports:
        - "5050:5050"
      restart: unless-stopped

    todoapp-postgres:
      image: postgres:16.13-bookworm
      container_name: todoapp-env-postgres
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      volumes:
        - pgdata:/var/lib/postgresql/data
      restart: unless-stopped

    todoapp-redis:
      image: redis:8.8.1
      container_name: todoapp-env-redis
      command: redis-server --requirepass ${REDIS_PASSWORD}
      volumes:
        - redis_data:/data
      restart: unless-stopped

    todoapp-postgres-migrate:
      image: migrate/migrate:v4.19.1
      volumes: 
        - ${PROJECT_ROOT}/migrations:/migrations

    port-forwarder:
      image: alpine/socat:1.8.0.3
      container_name: todoapp-env-port-forwarder
      entrypoint: | 
        /bin/sh -c "
          socat -d -d tcp-listen:5432,fork,reuseaddr tcp-connect:todoapp-postgres:5432 &
          socat -d -d tcp-listen:6379,fork,reuseaddr tcp-connect:todoapp-redis:6379 &
          wait
        "
      ports:
        - "127.0.0.1:5432:5432"
        - "127.0.0.1:6379:6379"

    swagger:
      build:
        context: ${PROJECT_ROOT}
        dockerfile_inline: |
          FROM golang:1.25.5-alpine
          RUN apk add --no-cache git
          RUN go install github.com/swaggo/swag/cmd/swag@v1.16.6
          WORKDIR /code
          ENTRYPOINT ["swag"]
      volumes:
        - ${PROJECT_ROOT}:/code

volumes:
  pgdata: {}
  redis_data: {}
  caddy_data: {}